version: '3.8'

services:
  app:
    build: .
    container_name: stamp_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/stamp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - stamp_network

  db:
    image: mariadb:10.6
    container_name: stamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stamp
    ports:
      - "3307:3306"
    networks:
      - stamp_network

networks:
  stamp_network:
