spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://odindb.cbc4us006q3x.ap-northeast-2.rds.amazonaws.com:3306/odin_stamp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: izongg
    password: Wdsa4608!